### ISSUE TITLE
btcd_lib missing

### ISSUE THREAD

**Issue by syahrul12345** [sarahc0nn0r/ultranet#1]
Hey,

I cant seem to build from source since the current btcd library doesnt have btcd_lib. Are you using a different version by any chance?

**Comment by sarahc0nn0r** [comment]
That's odd. It should be using a forked btcd library in the [vendor directory](https://github.com/sarahc0nn0r/ultranet/tree/master/vendor/github.com/btcsuite/btcd). 

Could you let me know exactly what command you're running and from what directory? I think it should work if you do the following:
$ cd $GOPATH/src/ultranet/
$ ./build.sh

If that works then this should work:
$ cd $GOPATH/src/ultranet/backend
$ go build

Let me know if you're still having trouble with the above commands.

**Comment by sarahc0nn0r** [comment]
Also sorry for the delay. I had a lot to do to prepare for the launch on Tuesday but should be faster to respond now.

**Comment by sarahc0nn0r** [comment]
Closing this for now. Let me know if my suggestion didn't fix your issue.
